services:
  cloudflare-ddns:
    container_name: CF-DDNS-Domains
    image: favonia/cloudflare-ddns:latest
    networks:
      - devrack
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: 'https://cdn.jsdelivr.net/gh/selfhst/icons/webp/cloudflare.webp'
    user: "${PUID}:${PGID}"
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true]
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - TZ=${TZ}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_KEY}
      - DOMAINS=${CLOUDFLARE_SUBDOMAIN_WWW}.${CLOUDFLARE_DOMAIN1},${CLOUDFLARE_DOMAIN1},${CLOUDFLARE_SUBDOMAIN_WWW}.${CLOUDFLARE_DOMAIN2},${CLOUDFLARE_DOMAIN2}
      - PROXIED=true
      - IP6_PROVIDER=none
      - DELETE_ON_STOP=false
    restart: always

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
