---
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    networks:
      - devrack
    env_file:
      - ../server.env
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:3001]'
      - net.unraid.docker.icon='https://cdn.jsdelivr.net/gh/selfhst/icons/webp/uptime-kuma.webp'
    ports:
      - 3001:3001
    volumes:
      - /mnt/user/appdata/external/uptime-kuma:/app/data
    restart: always

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
