---
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./phpmyadmin.env
    ports:
      - "${SERVER_IP}:8070:80/tcp"
    environment:
      - PMA_HOST: ${SERVER_IP}
      - PMA_PORT: 3306
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      - MYSQL_USER: ${MYSQL_USER}
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
