---
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6
    networks:
      - devrack
    env_file:
      - ./.env
    ports:
      - ${SERVER_IP}:1987:1987
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]/files/'
      - net.unraid.docker.icon='https://github.com/maschhoff/docker/raw/master/filebrowser/35781395.png'
    volumes:
      - /mnt/user/appdata/cloud/filebrowser/database:/database # location of database
      - /mnt/user/appdata/cloud/filebrowser/config:/config # location for pre-configured settings.json
      - /mnt/user/appdata/cloud/filebrowser/branding:/branding # branding location
      - /mnt/user/cloud:/cloud
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
