services:
  dawarich_redis:
   image: redis:7.4-alpine
   container_name: dawarich_redis
   command: redis-server
   networks:
      - devrack
   volumes:
     - /mnt/user/appdata/dawarich/dawarich_shared:/data
   restart: always
   healthcheck:
     test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
     interval: 10s
     retries: 5
     start_period: 30s
     timeout: 10s

  dawarich_db:
    image: postgis/postgis:17-3.5-alpine
    shm_size: 1G
    container_name: dawarich_db
    networks:
      - devrack
    volumes:
      - /mnt/user/appdata/dawarich/dawarich_db_data:/var/lib/postgresql/data
      - /mnt/user/appdata/dawarich/dawarich_shared:/var/shared
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.icon='https://cdn.jsdelivr.net/gh/selfhst/icons/webp/postgresql.webp'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dawarich_development" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  dawarich_app:
    image: freikin/dawarich:latest
    container_name: dawarich_app
    networks:
      - devrack
    volumes:
      - /mnt/user/appdata/dawarich/dawarich_public:/var/app/public
      - /mnt/user/appdata/dawarich/dawarich_watched:/var/app/tmp/imports/watched
      - /mnt/user/appdata/dawarich/dawarich_storage:/var/app/storage
      - /mnt/user/appdata/dawarich/dawarich_db_data:/dawarich_db_data
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:7654]'
      - net.unraid.docker.icon='https://cdn.jsdelivr.net/gh/selfhst/icons/webp/dawarich.webp'
    ports:
      - "${SERVER_IP}:7654:3000"
    stdin_open: true
    tty: true
    entrypoint: web-entrypoint.sh
    command: ['bin/rails', 'server', '-p', '3000', '-b', '::']
    restart: on-failure
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: dawarich_development
      # PostgreSQL database name for solid_queue
#      QUEUE_DATABASE_NAME: dawarich_development_queue
#      QUEUE_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
#      QUEUE_DATABASE_USERNAME: ${POSTGRES_USER}
#      QUEUE_DATABASE_PORT: 5432
#      QUEUE_DATABASE_HOST: dawarich_db
      # SQLite database paths for secondary databases
#      CACHE_DATABASE_PATH: /mnt/user/appdata/dawarich/dawarich_sqlite_data/dawarich_development_cache.sqlite3
#      CABLE_DATABASE_PATH: /mnt/user/appdata/dawarich/dawarich_sqlite_data/dawarich_development_cable.sqlite3
      MIN_MINUTES_SPENT_IN_CITY: 60
      APPLICATION_HOSTS: localhost
      TIME_ZONE: ${TZ}
      APPLICATION_PROTOCOL: http
      DISTANCE_UNIT: mi
      PROMETHEUS_EXPORTER_ENABLED: false
      PROMETHEUS_EXPORTER_PORT: 9394
      ENABLE_TELEMETRY: false
      SELF_HOSTED: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO - http://127.0.0.1:3000/api/v1/health | grep -q '\"status\"\\s*:\\s*\"ok\"'" ]
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 10s
    depends_on:
      dawarich_db:
        condition: service_healthy
      dawarich_redis:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4G'

  dawarich_sidekiq:
   image: freikin/dawarich:latest
   container_name: dawarich_sidekiq
   volumes:
     - /mnt/user/appdata/dawarich/dawarich_public:/var/app/public
     - /mnt/user/appdata/dawarich/dawarich_watched:/var/app/tmp/imports/watched
     - /mnt/user/appdata/dawarich/dawarich_storage:/var/app/storage
   networks:
      - devrack
   stdin_open: true
   tty: true
   entrypoint: sidekiq-entrypoint.sh
   command: ['sidekiq']
   restart: on-failure
   environment:
     RAILS_ENV: development
     REDIS_URL: redis://dawarich_redis:6379
     DATABASE_HOST: dawarich_db
     DATABASE_USERNAME: ${POSTGRES_USER}
     DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
     DATABASE_NAME: dawarich_development
     APPLICATION_HOSTS: localhost
     BACKGROUND_PROCESSING_CONCURRENCY: 3
     APPLICATION_PROTOCOL: http
     PROMETHEUS_EXPORTER_ENABLED: false
     PROMETHEUS_EXPORTER_PORT: 9394
     SELF_HOSTED: "true"
     STORE_GEODATA: "true"
   logging:
     driver: "json-file"
     options:
       max-size: "100m"
       max-file: "5"
   healthcheck:
     test: [ "CMD-SHELL", "pgrep -f sidekiq" ]
     interval: 10s
     retries: 30
     start_period: 30s
     timeout: 10s
   depends_on:
     dawarich_db:
       condition: service_healthy
       restart: true
     dawarich_redis:
       condition: service_healthy
       restart: true
     dawarich_app:
       condition: service_healthy
       restart: true

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
