---
services:

# beszel
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    networks:
      - devrack
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:8090]
      net.unraid.docker.icon: 'https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel-light.webp'
    ports:
      - '${SERVER_IP}:8090:8090'
    volumes:
      - /mnt/user/appdata/beszel_data:/beszel_data
    environment:
      TZ: ${TZ}
      DISABLE_PASSWORD_AUTH: 'false'
      AUTO_LOGIN: 'email@domain.tld'
      CHECK_UPDATES: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

# beszel-agent
  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    networks:
      - devrack
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.icon: 'https://cdn.jsdelivr.net/gh/selfhst/icons/webp/beszel.webp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ}
      LISTEN: 45876
      KEY: 'long-serial'
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
