services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin:latest
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:8096:8096"
      - "${SERVER_IP}:8920:8920" # HTTPS
      - "${SERVER_IP}:1900:1900/udp" # Service Discovery
    volumes:
      - /mnt/user/appdata/jellyfin:/config
      - /mnt/user/media/:/media
      - /mnt/user/media/metadata:/metadata
      - /mnt/user/scratch/jellyfin_transcodes:/config/data/transcodes
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    deploy:
      resources:
        limits:
          cpus: '4.0'
    labels:
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: 'http://[IP]:[PORT:8096]'
      net.unraid.docker.icon: 'https://static-00.iconduck.com/assets.00/jellyfin-icon-2048x2048-tf5ztk6m.png'
    restart: unless-stopped
networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
