---
services:
  pingvin-share:
    container_name: pingvin-share
    image: stonith404/pingvin-share
    env_file:
      - ./.env
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:4981:3000"
    volumes:
      - /mnt/user/appdata/cloud/pingvin/data/pingvin-share.db:/opt/app/backend/data/pingvin-share.db # make sure to create the file before starting the container
      - /mnt/user/appdata/cloud/pingvin/data/images:/opt/app/frontend/public/img
      - /mnt/scratch-disk/Scratch/Uploads:/opt/app/backend/data/uploads
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: unless-stopped
    depends_on:
      clamav:
        condition: service_healthy

# Optional: Add ClamAV (see README.md)
# ClamAV is currently only available for AMD64 see https://github.com/Cisco-Talos/clamav/issues/482
  clamav:
    container_name: clamav-pingvin
    image: clamav/clamav
    networks:
      - devrack
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
