---
services:

# Homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - devrack
    environment:
      - HOST_OS=Unraid
      - HOST_HOSTNAME=Alexandria
      - HOST_CONTAINERNAME=homepage
      - PORT=3000
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_ALLOWED_HOSTS=${SERVER_IP}:3000
    labels:
      - net.unraid.docker.managed=dockerman
      - net.unraid.docker.webui='http://[IP]:[PORT:3000]'
      - net.unraid.docker.icon='https://cdn.jsdelivr.net/gh/selfhst/icons/webp/homepage.webp'
    ports:
      - 3000:3000
    volumes:
      - /mnt/user/appdata/homepage/:/app/config
      #- /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
