---
services:
  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERBOSITY=-vv #optional
    volumes:
      - /mnt/user/appdata/security/fail2ban/config:/config
      - /var/log:/var/log:ro
      - /mnt/user/appdata/NginxProxyManager/log:/remotelogs/nginx:ro #optional
    restart: unless-stopped
