services:
  broker:
    container_name: paperless_redis
    image: docker.io/library/redis:7
    networks:
      - devrack
    env_file:
      - ../server.env
    volumes:
      -  /mnt/user/appdata/docs/paperless-ngx/redisdata:/data
    restart: unless-stopped

  db:
    container_name: paperless_postgres
    image: docker.io/library/postgres:16
    networks:
      - devrack
    env_file:
      - ../server.env
    volumes:
      - /mnt/user/appdata/docs/paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  webserver:
    container_name: paperless_ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    networks:
      - devrack
    env_file:
      - ../server.env
      - ./paperless-ngx.env
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "${SERVER_IP}:8138:8138"
    volumes:
      - /mnt/user/appdata/docs/paperless-ngx/data:/usr/src/paperless/data
      - /mnt/user/userShare/paperless:/usr/src/paperless/media # where documents are stored
      - /mnt/user/backups/paperless-ngx:/usr/src/paperless/export # when exported, documents, thumbs, metadata, and dB
      - /mnt/user/Scratch/Uploads:/usr/src/paperless/consume # Drop location
    environment:
      USERMAP_UID: ${USERMAP_UID}
      USERMAP_GID: ${USERMAP_GID}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_DBNAME: ${DB_NAME}
      PAPERLESS_DBUSER: ${DB_USER}
      PAPERLESS_DBPASS: ${DB_PASSWORD}
      PAPERLESS_PORT: 8138
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin
      PAPERLESS_APP_TITLE: "Document Vault"
      PAPERLESS_CONSUMER_RECURSIVE: true
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
      PAPERLESS_TASK_WORKERS: 4
      PAPERLESS_LOGROTATE_MAX_BACKUPS: 5
      PAPERLESS_FILENAME_FORMAT: "{{ correspondent }}/{{ document_type }}/{{ title }}_{{ created_year }}_{{ created_month }}_{{ created_day }}"
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 30
      PAPERLESS_CONSUMER_IGNORE_PATTERNS: "[\".DS_Store\", \".DS_STORE\", \"._*\", \".stfolder/*\", \".stversions/*\", \".localized/*\", \"desktop.ini\", \"@eaDir/*\", \"Thumbs.db\",\".Recycle.Bin\",\".Recycle.Bin/*\"]"
      PAPERLESS_DATE_ORDER: "MDY"
      # OCR Settings
      PAPERLESS_OCR_MODE: skip
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: never
      PAPERLESS_OCR_CLEAN: clean
    restart: unless-stopped

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    container_name: paperless_gotenberg
    networks:
      - devrack
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    volumes:
      - /mnt/user/appdata/docs/paperless-ngx/gotenberg:/gotenberg
    restart: unless-stopped

  tika:
    image: docker.io/apache/tika:latest
    container_name: paperless_tika
    networks:
      - devrack
    volumes:
      - /mnt/user/appdata/docs/paperless-ngx/tika:/tika
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
