## Required settings - move these to ENV if you want to check in this file
immich_api_key: ""
immich_url: "" # Use http://{URL}?album=shared for shared albums

## Clock
show_time: true
time_format: 24 # 12 or 24
show_date: true
date_format: YYYY/MM/DD

## Kiosk behaviour
refresh: 60 # in seconds
disable_screensaver: true # Ask browser to request a lock that prevents device screens from dimming or locking.
optimize_images: true # Whether Kiosk should resize images to match your browser screen dimensions for better performance.
use_gpu: true # Enable GPU acceleration for improved performance.

## Asset sources
show_archived: false # Allow assets marked as archived to be displayed.

## ID(s) of person or people to display
person:
  - "PERSON_ID"

## ID(s) of album or albums to display
album:
  - ""

## Album IDs to exclude from being shown. Albums in this list will be filtered from
## appearing in the frame even if they are included in the 'album' list.
album_order: random # random | newest | oldest
excluded_albums:
  - "ALBUM_ID"

## Date range or ranges to display
date:
  - "YYYY-MM-DD_to_YYYY-MM-DD"

memories: false # show memories

## UI
disable_ui: false # this is just a shortcut for all ui elements (show_time, show_date, show_image_time, show_image_date)
frameless: false # remove border around image and rounded corners.
hide_cursor: true # Hide cursor/mouse via CSS.
font_size: 100 # the base font size as a percentage. OMIT the % character
background_blur: true # display a blurred version of image as background
theme: fade # which theme to use. fade or solid
layout: single # which layout to use. single | splitview | splitview-landscape | portrait | landscape

## Sleep mode
sleep_start: 1800 # sleep mode start time
sleep_end: 0700 # sleep mode end time
sleep_icon: false

## Transition options
transition: fade # cross-fade, fade or none
fade_transition_duration: 1 # in seconds
cross_fade_transition_duration: 1 # in seconds

## Image display settings
show_progress: false # display a progress bar
image_fit: contain # none | contain | cover
image_effect: none # none | zoom | smart-zoom
image_effect_amount: 120
use_original_image: false # use the original file.

## Image METADATA
show_album_name: false
show_person_name: false
show_image_time: true
image_time_format: 24 # 12 or 24
show_image_date: true
image_date_format: YYYY-MM-DD
show_image_description: false
show_image_exif: true
show_image_location: true
hide_countries:
  - "country to hide"
show_image_id: false
show_more_info: false
show_more_info_image_link: false
show_more_info_qr_code: false

## Weather feature - you’ll need an API key from OpenWeatherMap
# weather:
#   - name: london
#     lat: 51.5285262
#     lon: -0.2663999
#     api: ""
#     unit: metric
#     lang: en

## Options that can NOT be changed via url params
kiosk:
  port: 3000
  watch_config: true
  fetched_assets_size: 1000
  http_timeout: 20
  password: ""
  cache: true # cache select api calls
  pre_fetch: true # fetch assets in the background
  asset_weighting: true # use weighting when picking assets
